version: 2.1
dependencies:
  pre:
    - rm -rf ~/.yarn
    - npm install -g yarn
    - yarn -v
  override:
    - yarn
  cache_directories:
    - ~/.cache/yarn

executors:
  node-executor:
    docker:
      - image: cimg/node:16.14
    working_directory: ~/circleCiTest
#  android-executor:
#   docker:
#    - image: findyourcanopy/buildfrontenv:android
#  working_directory: ~/circleCiTest
  ios-executor:
    macos:
      xcode: "13.3.0"
    working_directory: ~/circleCiTest

jobs:
  lint:
    executor: node-executor
    steps:
      - attach_workspace:
          at: ~/
      - run: yarn lint:ci
      - run: yarn stylelint:ci
  build:
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Update NPM
          command: "sudo npm install -g npm@5"
      - restore_cache:
          name: Restore yarn cache
          keys:
            - yarn-3-{{ arch }}-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
            - yarn-3-{{ arch }}-{{ checksum "package.json" }}-
      - run:
          name: "Install dependencies"
          command: |
            yarn install --frozen-lockfile --non-interactive --cache-folder ~/.cache/yarn
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run tests
          command: npm run test